### ISSUE TITLE
FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by huey735** [bisq-network/bisq-docs#153] opened 2019-08-18 07:01 UTC
I get the following error when I run './gradlew build' inside my /bisq-docs folder.
I used this script to install JAVA: https://github.com/bisq-network/bisq/blob/master/scripts/install_java.sh
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':asciidoctor'.
> Could not resolve all files for configuration ':asciidoctor'.
   > Could not resolve org.codehaus.groovy:groovy-all:2.3.9.
     Required by:
         project : > org.asciidoctor:asciidoctorj-groovy-dsl:1.0.0.Alpha2
      > Could not resolve org.codehaus.groovy:groovy-all:2.3.9.
         > Could not get resource 'https://jcenter.bintray.com/org/codehaus/groovy/groovy-all/2.3.9/groovy-all-2.3.9.pom'.
            > Could not GET 'https://jcenter.bintray.com/org/codehaus/groovy/groovy-all/2.3.9/groovy-all-2.3.9.pom'.
               > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
1 actionable task: 1 executed
```

@m52go pointed me to [this thread](https://stackoverflow.com/questions/21076179/pkix-path-building-failed-and-unable-to-find-valid-certification-path-to-requ) but it's beyond my understanding.

**Comment by m52go** [comment] 2019-08-22 03:03
@huey735 I was able to reproduce this issue on a fresh install of Ubuntu. Turns out the remedy was much simpler than what Googling indicated. Try #155 and see if it works for you.

**Comment by huey735** [comment] 2019-08-22 10:27
Thanks @m52go it worked!

**Comment by z16166** [comment] 2020-01-05 09:29
The build exception still exists for the latest master branch.


happy@ubuntu:~/bisq-docs$ gradle wrapper --gradle-version 2.10 -i
Starting Build
Settings evaluated using settings file '/master/settings.gradle'.
Projects loaded. Root project using build file '/home/happy/bisq-docs/build.gradle'.
Included projects: [root project 'bisq-docs']
Evaluating root project 'bisq-docs' using build file '/home/happy/bisq-docs/build.gradle'.
[Asciidoctor] asciidoctorj: 1.6.2
[Asciidoctor] asciidoctorj-groovy-dsl: 1.6.0
You are using one or more deprecated Asciidoctor task or plugins. These will be removed in a future release. To help you migrate we have compiled some tips for you based upon your current usage:

  - 'org.asciidoctor.convert' is deprecated. When you have time please switch over to 'org.asciidoctor.jvm.convert'.
  - jcenter() is no longer added by default. If you relied on this behaviour in the past, please add jcenter() to the repositories block.


All projects evaluated.
Selected primary task 'wrapper' from project :
Tasks to be executed: [task ':wrapper']
:wrapper (Thread[main,5,main]) started.
:wrapper
Skipping task ':wrapper' as it is up-to-date (took 0.037 secs).
:wrapper UP-TO-DATE
:wrapper (Thread[main,5,main]) completed. Took 0.043 secs.

BUILD SUCCESSFUL

Total time: 2.06 secs

This build could be faster, please consider using the Gradle Daemon: https://docs.gradle.org/2.10/userguide/gradle_daemon.html
happy@ubuntu:~/bisq-docs$ ./gradlew build -i
Starting Build
Settings evaluated using settings file '/master/settings.gradle'.
Projects loaded. Root project using build file '/home/happy/bisq-docs/build.gradle'.
Included projects: [root project 'bisq-docs']
Evaluating root project 'bisq-docs' using build file '/home/happy/bisq-docs/build.gradle'.
[Asciidoctor] asciidoctorj: 1.6.2
[Asciidoctor] asciidoctorj-groovy-dsl: 1.6.0
You are using one or more deprecated Asciidoctor task or plugins. These will be removed in a future release. To help you migrate we have compiled some tips for you based upon your current usage:

  - 'org.asciidoctor.convert' is deprecated. When you have time please switch over to 'org.asciidoctor.jvm.convert'.
  - jcenter() is no longer added by default. If you relied on this behaviour in the past, please add jcenter() to the repositories block.


All projects evaluated.
Selected primary task 'build' from project :
Tasks to be executed: [task ':asciidoctor', task ':assemble', task ':check', task ':build']
:asciidoctor (Thread[main,5,main]) started.
:asciidoctor
Executing task ':asciidoctor' (up-to-date check took 0.1 secs) due to:
  No history is available.
:asciidoctor FAILED
:asciidoctor (Thread[main,5,main]) completed. Took 0.173 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':asciidoctor'.
> org/gradle/internal/scripts/ScriptOrigin

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output.

BUILD FAILED

Total time: 2.307 secs

**Comment by m52go** [comment] 2020-01-10 18:22
@z16166 hi, what version of OpenJDK are you using? If newer than OpenJDK 10, Gradle version might have been the issue. 

Please see my PR:
https://github.com/bisq-network/bisq-docs/pull/190

**Comment by m52go** [comment] 2020-01-16 02:04
Closing, as the PR mentioned above as a solution is now merged. Please make a new issue if the problem persists.

**Closed by m52go** 2020-01-16 02:04 UTC
